language: generic
sudo: required
services:
  - docker

before_install:
  # Build client in readiness for unit tests
  - docker build -t paulom77/react-test -f ./client/Dockerfile.dev ./client

script:
  # Now run those unit tests
  - docker run -e CI=true paulom77/react-test npm run test
    
after_success:
  # Build docker images
  - docker build -t paulom77/multi-client ./client 
  - docker build -t paulom77/multi-nginx ./nginx 
  - docker build -t paulom77/multi-server ./server 
  - docker build -t paulom77/multi-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push to docker hub
  - docker push paulom77/multi-client
  - docker push paulom77/multi-nginx
  - docker push paulom77/multi-server
  - docker push paulom77/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-600845931400"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
    